### ISSUE TITLE
Posterior predictive intervals with overdispersion models

### ISSUE THREAD

**Issue by andrjohns** [nhs-r-community/FunnelPlotR#29]
Hi Chris, my organisation uses your package for funnel plot control limits but have been having some issues with overdispersed data (even with overdispersion adjustments). I've put together a new approach which uses different distributions for overdispersion (i.e., the beta-binomial and negative-binomial) to construct the control limits, which seems to be working very well for our data.

If the approach seems reasonable to you, I'd like to open some PRs to integrate it into the package so our workflow stays consistent. I've put together a summary and some examples comparing the results [in this document](https://htmlpreview.github.io/?https://github.com/andrjohns/LimitsTemporary/blob/main/PPD-Control-Limits.html)

If you've got the time would you be able to have a look? I'm extremely new to this area, so feel free to let me know if I've made any basic mistakes.

**Comment by chrismainey** [comment]
Hi Andrew, thank you so much for your interest.  The package has grown out of my own use of these plots in a fairly limited context. I was fortunate to have a discussions with Prof. Spiegelhalter at the end of last year, and he was also happy to contribute some guidance to help generalise the package and to lend expertise.  I'd also appreciate any feedback you have.

I'd be very happy for you to build enhancements, but I'm a bit limited on capacity at the moment.  Please forgive my bouncing the request, but I'll be able to look through you document and learn more in a couple of weeks time.  I like the idea of different distributions. I have some experience with the negative binomial, and could see how that would be helpful.

I'd been trying not to alert the UI too much, bit I've had to make a number of changes since the last CRAN release, as my team have used it a bit and needed some tweaks.  You might find it gives odd error messages, or takes different arguments. Feel free to file issues, or make PRs if you spot anything.

**Comment by andrjohns** [comment]
Hi Chris (missed the notification of your reply sorry!). Not a problem at all! I'll keep getting familiar with the package and raising issues/PRs as I come across things. 

Thanks for a great package!
